// Code generated by protoc-gen-go-senz. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package example

import (
	"fmt"

	typepb "github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1"
	"google.golang.org/protobuf/proto"
)

var (
	_ typepb.Empty
	_ fmt.Stringer
	_ proto.Message
)

var metadata_example = &typepb.XMeta{
	ServiceName: "SENTINEZ // EDGE",
	ServiceKind: typepb.Kind_KIND_GATEWAY_EDGE,
	ServiceKey:  "sentinez.edge.v1",
}

func GetMetaExample() *typepb.XMeta {
	return proto.Clone(metadata_example).(*typepb.XMeta)
}

func GetMetaExampleServiceName() string {
	return metadata_example.GetServiceName()
}

func GetMetaExampleServiceKind() typepb.Kind {
	return metadata_example.GetServiceKind()
}

func GetMetaExampleServiceKey() string {
	return metadata_example.GetServiceKey()
}

const (
	Hello_F1 = "f_1"
	Hello_F2 = "f_2"
)
