// Code generated by protoc-gen-go-senz. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package example

import (
	"fmt"

	typepb "github.com/sentinez/sentinez/api/proto/sentinez/types/v1"
	"google.golang.org/protobuf/proto"
)

var (
	_ typepb.Empty
	_ fmt.Stringer
	_ proto.Message
)

var metadata_example = &typepb.XMeta{
	ServiceName: "SENTINEZ // EDGE",
	ServiceZone: typepb.Zone_ZONE_DEMILITARIZED,
	ServiceKey:  "sentinez.dmz.edge.v1",
}

func GetMetaExample() *typepb.XMeta {
	return proto.Clone(metadata_example).(*typepb.XMeta)
}

func GetMetaExampleServiceName() string {
	return metadata_example.GetServiceName()
}

func GetMetaExampleServiceZone() typepb.Zone {
	return metadata_example.GetServiceZone()
}

func GetMetaExampleServiceKey() string {
	return metadata_example.GetServiceKey()
}

const (
	Hello_F1 = "f_1"
	Hello_F2 = "f_2"
)

func GetExampleServiceCreate() *typepb.XMethod {
	return &typepb.XMethod{
		Consoles: []typepb.Console{
			typepb.Console_CONSOLE_PORTAL,
		},
	}
}

func GetExampleServiceDelete() *typepb.XMethod {
	return &typepb.XMethod{
		Consoles: []typepb.Console{
			typepb.Console_CONSOLE_PORTAL,
			typepb.Console_CONSOLE_ADMIN,
		},
	}
}

func GetExampleServiceIgnored() *typepb.XMethod {
	return &typepb.XMethod{
		Ignore: true,
	}
}
