syntax = "proto3";

package example;

import "google/protobuf/descriptor.proto";
import "google/protobuf/empty.proto";
import "sentinez/types/v1/known.proto";
import "sentinez/types/v1/options.proto";

option go_package = "github.com/sentinez/sentinez/staging/src/github.com/sentinez/tools/example";
option (sentinez.types.v1.x_meta) = {
  service_name: "SENTINEZ // EDGE"
  service_kind: KIND_GATEWAY_EDGE
  service_key: "sentinez.dmz.edge.v1"
};

message Hello {
  option (sentinez.types.v1.x_message).database_model = true;
  string f_1 = 1;
  string f_2 = 2;
}

service ExampleService {
  rpc Create(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (sentinez.types.v1.x_method) = {
      consoles: [ CONSOLE_PORTAL ]
    };
  }

  rpc Delete(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (sentinez.types.v1.x_method) = {
      consoles: [ CONSOLE_PORTAL, CONSOLE_ADMIN ]
    };
  }

  rpc Ignored(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (sentinez.types.v1.x_method) = {
      ignore: true
    };
  }
}
