// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: example.proto

package example

import (
	_ "github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F_1           string                 `protobuf:"bytes,1,opt,name=f_1,json=f1,proto3" json:"f_1,omitempty"`
	F_2           string                 `protobuf:"bytes,2,opt,name=f_2,json=f2,proto3" json:"f_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetF_1() string {
	if x != nil {
		return x.F_1
	}
	return ""
}

func (x *Hello) GetF_2() string {
	if x != nil {
		return x.F_2
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\aexample\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dsentinez/types/v1/known.proto\x1a\x1fsentinez/types/v1/options.proto\"1\n" +
	"\x05Hello\x12\x0f\n" +
	"\x03f_1\x18\x01 \x01(\tR\x02f1\x12\x0f\n" +
	"\x03f_2\x18\x02 \x01(\tR\x02f2:\x06\xca\xf3\x18\x02\b\x012\xda\x01\n" +
	"\x0eExampleService\x12A\n" +
	"\x06Create\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\a\x8a\xb5\x18\x03\x12\x01\x01\x12B\n" +
	"\x06Delete\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\b\x8a\xb5\x18\x04\x12\x02\x01\x02\x12A\n" +
	"\aIgnored\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x06\x8a\xb5\x18\x02\b\x01Bv\x8a\xb2\x19&\n" +
	"\x10SENTINEZ // EDGE\x10\x02\x1a\x10sentinez.edge.v1ZJgithub.com/sentinez/sentinez/staging/src/github.com/sentinez/tools/exampleb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_proto_goTypes = []any{
	(*Hello)(nil),         // 0: example.Hello
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_example_proto_depIdxs = []int32{
	1, // 0: example.ExampleService.Create:input_type -> google.protobuf.Empty
	1, // 1: example.ExampleService.Delete:input_type -> google.protobuf.Empty
	1, // 2: example.ExampleService.Ignored:input_type -> google.protobuf.Empty
	1, // 3: example.ExampleService.Create:output_type -> google.protobuf.Empty
	1, // 4: example.ExampleService.Delete:output_type -> google.protobuf.Empty
	1, // 5: example.ExampleService.Ignored:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
