package senzmeta

import (
	"path/filepath"
	"strconv"
	"strings"

	commonpb "github.com/sentinez/sentinez/api/gen/go/sentinez/types/common/v1"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

func GenerateSentinezOptionFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {

	caser := cases.Title(language.Und)

	filename := file.GeneratedFilenamePrefix + "_senz_meta.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-senz-meta. DO NOT EDIT.")
	g.P("// Copyright 2025 Duc-Hung Ho")
	g.P()

	g.P("package ", file.GoPackageName)
	g.P("\n")
	g.P("import (")
	g.P("\t\"fmt\"\n")
	g.P()
	g.P("\tcommonpb \"github.com/sentinez/sentinez/api/gen/go/sentinez/types/common/v1\"")
	g.P("\t\"google.golang.org/protobuf/proto\"")
	g.P()
	g.P(")")
	g.P("\n")
	g.P("var (")
	g.P("\t_ commonpb.Empty")
	g.P("\t_ fmt.Stringer")
	g.P("\t_ proto.Message")
	g.P(")")
	g.P("\n")

	opts := file.Proto.GetOptions()
	if !proto.HasExtension(opts, commonpb.E_XMeta) {
		return nil
	}

	ext, ok := proto.GetExtension(opts, commonpb.E_XMeta).(*commonpb.XMeta)
	if !ok || ext == nil {
		return nil
	}

	name := strings.TrimSuffix(filepath.Base(file.Desc.Path()), ".proto")

	g.P()

	g.P("var metadata_", name, " = &commonpb.XMeta{")
	g.P("\tServiceName: ", strconv.Quote(ext.GetServiceName()), ",")
	g.P("\tServiceKind: commonpb.Kind_", ext.GetServiceKind(), ",")
	g.P("\tServiceKey:  ", strconv.Quote(ext.GetServiceKey()), ",")
	g.P("}")
	g.P()
	g.P("func GetMeta", caser.String(name), "() *commonpb.XMeta {")
	g.P("\treturn proto.Clone(metadata_", name, ").(*commonpb.XMeta)")
	g.P("}")
	g.P()
	g.P("func GetMeta", caser.String(name), "ServiceName() string {")
	g.P("\treturn metadata_", name, ".GetServiceName()")
	g.P("}")
	g.P()
	g.P("func GetMeta", caser.String(name), "ServiceKind() commonpb.Kind {")
	g.P("\treturn metadata_", name, ".GetServiceKind()")
	g.P("}")
	g.P()
	g.P("func GetMeta", caser.String(name), "ServiceKey() string {")
	g.P("\treturn metadata_", name, ".GetServiceKey()")
	g.P("}")
	g.P()
	return g
}
