package senz

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	typepb "github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1"
	"github.com/sentinez/tools/internal/utils"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

func GenerateSentinezOptionFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_senz.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	writeHeader(g, file)
	writeImports(g)
	writeTypeAssertions(g)

	if opts := file.Proto.GetOptions(); proto.HasExtension(opts, typepb.E_XMeta) {
		meta, ok := proto.GetExtension(opts, typepb.E_XMeta).(*typepb.XMeta)
		if !ok || meta == nil {
			return g
		}

		name := protoBaseName(file.Desc.Path())
		caser := cases.Title(language.Und)

		writeMetadata(g, name, meta)
		writeMetaGetters(g, caser.String(name))
	}

	g.P()

	generateExportedFields(g, file)
	generateDatabaseModelFields(g, file)
	generateMethodRequirementGetters(g, file)

	return g
}

func writeHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-go-senz. DO NOT EDIT.")
	g.P("// Copyright 2025 Duc-Hung Ho")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func writeImports(g *protogen.GeneratedFile) {
	g.P("import (")
	g.P(`	"fmt"`)
	g.P()
	g.P(`	typepb "github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()
}

func writeTypeAssertions(g *protogen.GeneratedFile) {
	g.P("var (")
	g.P("	_ typepb.Empty")
	g.P("	_ fmt.Stringer")
	g.P("	_ proto.Message")
	g.P(")")
	g.P()
}

func writeMetadata(g *protogen.GeneratedFile, name string, meta *typepb.XMeta) {
	g.P("var metadata_", name, " = &typepb.XMeta{")
	g.P("	ServiceName: ", strconv.Quote(meta.GetServiceName()), ",")
	g.P("	ServiceKind: typepb.Kind_", meta.GetServiceKind(), ",")
	g.P("	ServiceKey:  ", strconv.Quote(meta.GetServiceKey()), ",")
	g.P("}")
}

func writeMetaGetters(g *protogen.GeneratedFile, name string) {
	g.P()
	g.P("func GetMeta", name, "() *typepb.XMeta {")
	g.P("	return proto.Clone(metadata_", strings.ToLower(name), ").(*typepb.XMeta)")
	g.P("}")
	g.P()
	g.P("func GetMeta", name, "ServiceName() string {")
	g.P("	return metadata_", strings.ToLower(name), ".GetServiceName()")
	g.P("}")
	g.P()
	g.P("func GetMeta", name, "ServiceKind() typepb.Kind {")
	g.P("	return metadata_", strings.ToLower(name), ".GetServiceKind()")
	g.P("}")
	g.P()
	g.P("func GetMeta", name, "ServiceKey() string {")
	g.P("	return metadata_", strings.ToLower(name), ".GetServiceKey()")
	g.P("}")
}

func generateExportedFields(g *protogen.GeneratedFile, file *protogen.File) {
	for _, msg := range file.Messages {
		xmsg := getXMessage(msg)
		if xmsg == nil || !xmsg.GetExportField() {
			continue
		}

		writeFieldConstants(
			g,
			msg,
			func(msgName, fieldName string) string {
				return fmt.Sprintf("X%s_%s", msgName, utils.SnakeToPascal(fieldName))
			},
		)
	}
}

func generateDatabaseModelFields(g *protogen.GeneratedFile, file *protogen.File) {
	for _, msg := range file.Messages {
		xmsg := getXMessage(msg)
		if xmsg == nil || !xmsg.DatabaseModel {
			continue
		}

		writeFieldConstants(
			g,
			msg,
			func(msgName, fieldName string) string {
				return fmt.Sprintf("%s_%s", msgName, utils.SnakeToPascal(fieldName))
			},
		)
	}
}

func writeFieldConstants(
	g *protogen.GeneratedFile,
	msg *protogen.Message,
	nameFn func(msgName, fieldName string) string,
) {
	g.P("const (")
	for _, field := range msg.Fields {
		fieldName := string(field.Desc.Name())
		constName := nameFn(msg.GoIdent.GoName, fieldName)
		g.P(fmt.Sprintf(`	%s = "%s"`, constName, fieldName))
	}
	g.P(")")
	g.P()
}

func getXMessage(msg *protogen.Message) *typepb.XMessage {
	opts := msg.Desc.Options()
	ext, ok := proto.GetExtension(opts, typepb.E_XMessage).(*typepb.XMessage)
	if !ok {
		return nil
	}
	return ext
}

func protoBaseName(path string) string {
	return strings.TrimSuffix(filepath.Base(path), ".proto")
}

func generateMethodRequirementGetters(g *protogen.GeneratedFile, file *protogen.File) {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			xmethod := getXMethod(method)
			if xmethod == nil || (!xmethod.Ignore && len(xmethod.Consoles) == 0) {
				continue
			}

			writeMethodRequirementGetter(g, service, method, xmethod)
		}
	}
}

func writeMethodRequirementGetter(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, xmethod *typepb.XMethod) {
	serviceName := service.GoName
	methodName := method.GoName
	funcName := fmt.Sprintf("Get%s%s", serviceName, methodName)

	g.P(fmt.Sprintf("func %s() *typepb.XMethod {", funcName))
	g.P("\treturn &typepb.XMethod{")

	if xmethod.Ignore {
		g.P("\t\tIgnore: true,")
	}

	if len(xmethod.Consoles) > 0 {
		g.P("\t\tConsoles: []typepb.Console{")
		for _, c := range xmethod.Consoles {
			g.P(fmt.Sprintf("\t\t\ttypepb.Console_%s,", c.String()))
		}
		g.P("\t\t},")
	}

	g.P("\t}")
	g.P("}")

	g.P()
}

func getXMethod(method *protogen.Method) *typepb.XMethod {
	opts := method.Desc.Options()
	if !proto.HasExtension(opts, typepb.E_XMethod) {
		return nil
	}
	ext, ok := proto.GetExtension(opts, typepb.E_XMethod).(*typepb.XMethod)
	if !ok {
		return nil
	}
	return ext
}
