// Copyright 2025 Duc-Hung Ho.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package senzmsg

import (
	"fmt"

	typepb "github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1"
	"github.com/sentinez/tools/internal/utils"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

// GenerateSenzMsgFile generates a _senz_msg.pb.go file containing gRPC service definitions.
func GenerateSenzMsgFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_senz_msg.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-senz-msg. DO NOT EDIT.")
	g.P("// Copyright 2025 Duc-Hung Ho")
	g.P()

	g.P("package ", file.GoPackageName)
	g.P("\n")
	g.P("import (")
	g.P("\t\"fmt\"\n")
	g.P()
	g.P("\ttypepb \"github.com/sentinez/sentinez/api/gen/go/sentinez/types/v1\"\n")
	g.P(")")
	g.P("\n")
	g.P("var (")
	g.P("\t_ typepb.Empty")
	g.P("\t_ fmt.Stringer")
	g.P(")")
	g.P("\n")

	objectExportFieldGen(g, file)
	objectModelGen(g, file)
	return g
}

func objectExportFieldGen(g *protogen.GeneratedFile, file *protogen.File) {
	for _, message := range file.Messages {
		opts := message.Desc.Options()

		ext, ok := proto.GetExtension(opts, typepb.E_XMessage).(*typepb.XMessage)
		if !ok || ext == nil {
			continue
		}

		if ext.GetExportField() {
			g.P("const (")
			for _, field := range message.Fields {
				fieldName := string(field.Desc.Name())
				constName := fmt.Sprintf("X%s_%s", message.GoIdent.GoName, utils.SnakeToPascal(fieldName))
				g.P(fmt.Sprintf("    %s = \"%s\"", constName, fieldName))
			}
			g.P(")")
			g.P("\n")
		}
	}
}

func objectModelGen(g *protogen.GeneratedFile, file *protogen.File) {
	for _, message := range file.Messages {
		opts := message.Desc.Options()

		ext, ok := proto.GetExtension(opts, typepb.E_XMessage).(*typepb.XMessage)
		if !ok || ext == nil {
			continue
		}

		if ext.DatabaseModel {
			g.P("const (")
			for _, field := range message.Fields {
				fieldName := string(field.Desc.Name())
				constName := fmt.Sprintf("%s_%s", message.GoIdent.GoName, utils.SnakeToPascal(fieldName))
				g.P(fmt.Sprintf("    %s = \"%s\"", constName, fieldName))
			}
			g.P(")")
			g.P("\n")
		}
	}
}
