package template

var SentinezRuleFunc = `
// Code generated by ruleparser-sentinez. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho
package rules

import (
	rulepb "github.com/sentinez/sentinez/api/gen/go/sentinez/secure/rule/v1"
)

{{ $outer := . }}

const {{ .Name }}Version = {{ .Version | printf "%q" }}

var {{ .Name }}Order = []func() *rulepb.CoreRule{
	{{- range $i, $rule := .Rules }}
	{{- $ids := $rule.Actions.Fields.Id }}
	{{- if $ids }}
	R{{ index $ids 0 }},
	{{- else }}
	{{ $.Name }}Maker_{{ $i }},
	{{- end }}
	{{- end }}
}

var {{ .Name }} = map[string]*rulepb.CoreRule{
	{{- range $i, $rule := .Rules }}
	{{- $ids := $rule.Actions.Fields.Id }}
	{{- if $ids }}
	"{{ index $ids 0 }}": R{{ index $ids 0 }}(),
	{{- else }}
	"{{ $.Name }}Maker_{{ $i }}": {{ $.Name }}Maker_{{ $i }}(),
	{{- end }}
	{{ end }}
}

{{ range $i, $rule := .Rules }}
{{- $ids := $rule.Actions.Fields.Id }}
{{- if $ids }}
// R{{ index $ids 0 }} returns rule with ID {{ index $ids 0 }}
func R{{ index $ids 0 }}() *rulepb.CoreRule {
{{- else }}
// {{ $.Name }}Maker_{{ $i }} returns rule without ID
func {{ $.Name }}Maker_{{ $i }}() *rulepb.CoreRule {
{{- end }}
	return &rulepb.CoreRule{
		Actions: &rulepb.RuleAction{
			Statement: {{ $rule.Actions.Statement | base64Encode | printf "%q" }},
			{{- if $rule.Actions.Fields }}
			Fields: &rulepb.RuleActionField{
				{{- if $rule.Actions.Fields.Id }}Id: []string{ {{ range $rule.Actions.Fields.Id }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Msg }}Msg: []string{ {{ range $rule.Actions.Fields.Msg }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Phase }}Phase: []string{ {{ range $rule.Actions.Fields.Phase }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Tag }}Tag: []string{ {{ range $rule.Actions.Fields.Tag }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.T }}T: []string{ {{ range $rule.Actions.Fields.T }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Ver }}Ver: []string{ {{ range $rule.Actions.Fields.Ver }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Severity }}Severity: []string{ {{ range $rule.Actions.Fields.Severity }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Setvar }}Setvar: []string{ {{ range $rule.Actions.Fields.Setvar }}{{ printf "%q" . }},{{ end }} },{{ end }}
				{{- if $rule.Actions.Fields.Logdata }}Logdata: []string{ {{ range $rule.Actions.Fields.Logdata }}{{ printf "%q" . }},{{ end }} },{{ end }}
			},
			{{- end }}
		},
		Configuration: "{{ $rule.Configuration | base64Encode }}",
		Level: {{ $rule.Level | printf "%q" }},
	}
}
{{- end }}

`
